dynamic linking: fix missing dl library
Building with GCC 4.7.2 on Linux results in a linker error (see below). It is
suggested to explicitly link against the dl library:
https://gist.github.com/kwk/3595733

[6/54] Linking CXX executable test/test_class_info
FAILED: : && /usr/bin/c++   -Wall -Wextra -Wno-deprecated-declarations -Wlogical-op -Wmissing-declarations -Wsign-conversion -pedantic -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Winit-self -Wformat=2 -Wmissing-include-dirs -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-promo -Wstrict-null-sentinel -Wstrict-overflow=5 -Wno-long-long   test/CMakeFiles/test_class_info.dir/test_class_info.cpp.o  -o test/test_class_info  -rdynamic test/libtest_main.a src/libluabind09.a .../lua-5.2.2/lib/liblua.a -lm -lm && :
.../lua-5.2.2/lib/liblua.a(loadlib.o): In function `ll_loadfunc':
loadlib.c:(.text+0x4d2): undefined reference to `dlsym'
loadlib.c:(.text+0x521): undefined reference to `dlerror'
loadlib.c:(.text+0x556): undefined reference to `dlopen'
loadlib.c:(.text+0x5ce): undefined reference to `dlerror'
.../lua-5.2.2/lib/liblua.a(loadlib.o): In function `gctm':
loadlib.c:(.text+0x8a0): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status